/*

 FARM_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : Z:\home\mkremer\workspaces\untitled_gb_game\farm_city_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define FarmMapWidth 32
#define FarmMapHeight 32
#define FarmMapBank 0

extern unsigned char FarmMap[];

/* End of FARM_MAP.H */
